### ISSUE TITLE
FE: Share music dialog

### ISSUE THREAD

**Issue by aeciorc** [hatchways/team-cupcake#13]
__Overview__
User clicks on the share music button. It opens a dialog with a search bar. User can search for music using the spotify API. After selecting a song, the details are displayed as in this image:
https://drive.google.com/file/d/1ABoGxJ0gdSlhOV1ina8ksyO8tDgauCy3/view?usp=sharing
User can add a description and share it.

Since we don't have a mockup for the initial part of this feature (searching songs), you're free to implement that as you wish. For the remaining part, make sure it resembles to mockup as closely as possible

The app is still not connected to Spotify, so for now you need to mock that API call
Create some mock data for the search. The search should filter that data and show the results. , Selecting a result should display its details as in the mockup, but the "upload image" button doesn't need to work yet. After clicking on "Share", the post should become visible on the user profile, however it does not need talk to the backend yet, since this hasn't been implemented

**Comment by dipshojol** [comment]
it look like nav bar. do you want the dialog containing another nav bar?  @aeciorc

**Comment by aeciorc** [comment]
@dipshojol No, just the dialog at the bottom
